#! /bin/sh
set -e

case "$1" in
    start)
        echo "loading aesd-char-driver"
        aesdchar_load
        ;;
    stop)
        echo "unloading aesd-char-driver"
        aesdchar_unload
        ;;
    *)
        echo "usage: $0 {start|stop}"
        exit 1
esac
exit 0
